name: Publish Package

on:
  release:
    types: [published]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'
      
      - name: Add Poetry Plugin
        run: |
          poetry self add "poetry-dynamic-versioning[plugin]" &&
          poetry config repositories.testpypi https://test.pypi.org/legacy/ &&
          poetry config pypi-token.testpypi "${{ secrets.PYPI_TOKEN }}"

      - name: Build
        run: poetry build

      - name: Publish
        run: poetry publish -r testpypi
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
